config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :animations do
  end

  resources :princesses do
  end

  resources :maps do
  end

  resources :weapons do
  end
end

app/models/animations.rb
class Animations < ApplicationRecord
    validates :cn_name,  :presence => true
    def self.test
        puts "this is test"
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/princess.rb
class Princess < ApplicationRecord
    validates :cn_name,  :presence => true
    mount_uploader :icon, AvatarUploader
end

app/models/user.rb
class User < ApplicationRecord
    def self.test
        puts "this is test"
    end

    def follow!(user)
        $redis.multi do
            $redis.sadd(self.redis_key(:following), user.id)
            $redis.sadd(user.redis_key(:followers), self.id)
        end
    end

    # unfollow a user
    def unfollow!(user)
        $redis.multi do
            $redis.srem(self.redis_key(:following), user.id)
            $redis.srem(user.redis_key(:followers), self.id)
        end
    end

    # users that self follows
    def followers
        user_ids = $redis.smembers(self.redis_key(:followers))
        User.where(:id => user_ids)
    end

    # users that follow self
    def following
        user_ids = $redis.smembers(self.redis_key(:following))
        User.where(:id => user_ids)
    end

    # users who follow and are being followed by self
    def friends
        user_ids = $redis.sinter(self.redis_key(:following), self.redis_key(:followers))
        User.where(:id => user_ids)
    end

    # does the user follow self
    def followed_by?(user)
        $redis.sismember(self.redis_key(:followers), user.id)
    end

    # does self follow user
    def following?(user)
        $redis.sismember(self.redis_key(:following), user.id)
    end

    # number of followers
    def followers_count
        $redis.scard(self.redis_key(:followers))
    end

    # number of users being followed
    def following_count
        $redis.scard(self.redis_key(:following))
    end

    # helper method to generate redis keys
    def redis_key(str)
        "user:#{self.id}:#{str}"
    end
end

app/controllers/animations_controller.rb
class AnimationsController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @princesses = Princess.all
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
    def index
        
    end
end

app/controllers/princesses_controller.rb
class PrincessesController < ApplicationController
    def index
        @princesses = Princess.all
    end

    def new
        @princess = Princess.new
    end

    def create
        ActiveRecord::Base.transaction do
            begin
                @status = true
                @princess = Princess.new
                @princess.update_attributes(princess_params)
            rescue  => e
                @status = false
                flash[:notice] = e.message
            end
            if @status
                redirect_to princesses_path
            else
                render "new"
            end
        end
    end

    def princess_params
        params.require(:princess).permit(:cn_name,:icon)
    end
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
    def index
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/animations/index.html.erb
<img src="/assets/jk_leg.gif">

app/views/home/index.html.erb
<div class="header-bottom">  
	 <div class="wrap">
		<div class="header-left" id="home">
		  <section>
			<ul class="lb-album" >
				<%if @princesses.count > 0%>
					<%@princesses.each do |princess|%>
						<li>
							<a href="#image-1">
								<img src="<%=princess.icon_url%>" alt="image01">
								<span><%=princess.cn_name%></span>
							</a>
							<div class="lb-overlay" id="image-1">
								<a href="#page" class="lb-close">x Close</a>
								<img src="<%=princess.icon_url%>" alt="image01">
								<div>
									<h3>pointe <span>/point/</span></h3>
									<p>Dance performed on the tips of the toes</p>
								</div>
							</div>
						</li>
					<%end%>
				<%end%>
				<div class="clear"></div>
			</ul>
		</section>
		<div class="clear"></div>
		</div>
 	</div>
 </div>
 <div class="about-top" id="about">
	 <div class="wrap">
		<div class="intro">
			<h2 class="title">About Us</h2>
			<h3 class="subtitle">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo.</h3>
		</div>
		<div class="section group">
			<div class="col_1_of_3 span_1_of_3">
				<h3>Our philosophy</h3>
				<p class="small_margin"><span class="highlight">aliquam erat volutpat</span> nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor<span class="highlight">hendrerit in vulputate</span>augue duis dolore te feugait nulla facilisi.</p>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit.</p>
			</div>
			<div class="col_1_of_3 span_1_of_3">
				<h3>Our Mission</h3>
				<p class="small_margin">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p>
				<span class="italic">Eodem modo typi, quisty nunc nobis videntur parum clarits, it solemnes fiant futurum laris dolore magna utims et aliquam erat ipsum sit amet, consectetuer adipisci elit wisi euismod.</span>
			</div>
			<div class="col_1_of_3 span_1_of_3">
				<h3>Our Skills</h3>
				<div class="skills">
					<div style="width:85%"><p class="white">Lorem ipsum dolor ( 85% )</p></div>
				</div>
				<div class="skills">
					<div style="width:75%"><p class="white">Lorem ipsum dolor ( 75% )</p></div>
				</div>
				<div class="skills">
					<div style="width:90%"><p class="white">Lorem ipsum dolor ( 90% )</p></div>
				</div>
				<div class="skills">
					<div style="width:70%"><p class="white">Lorem ipsum dolor ( 70% )</p></div>
				</div>
			</div>
			<div class="clear"></div>
		</div>
		<div class="twelvecol">
			<div class="blockquote">
				<span>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but is also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of the Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software.</span>
			</div>
		</div>
		 <div class="section group">
				<div class="col_1_of_3 span_1_of_3">
					<ul class="comment">
						<li class="date">
							<div class="value">04 June 15</div>
							<div class="arrow_date"></div>
						</li>
						<li class="comments_number"><a href="#" title="2 comments">2</a></li>
					</ul>
					<div class="grid_img">
						<img src="/assets/pic14.jpg" alt="">
					</div>
				</div>
				<div class="col_1_of_3 span_1_of_3">
					 <ul class="comment">
						<li class="date">
							<div class="value">04 June 15</div>
							<div class="arrow_date"></div>
						</li>
						<li class="comments_number"><a href="#" title="2 comments">2</a></li>
					</ul>
					<div class="grid_img">
						<img src="/assets/pic15.jpg" alt="">
					</div>
				</div>
				<div class="col_1_of_3 span_1_of_3">
					 <ul class="comment">
						<li class="date">
							<div class="value">04 June 15</div>
							<div class="arrow_date"></div>
						</li>
						<li class="comments_number"><a href="#" title="2 comments">2</a></li>
					</ul>
					<div class="grid_img">
						<img src="/assets/pic16.jpg" alt="">
					</div>
				</div>
				<div class="clear"></div>
		</div>
	</div>
  </div>
	<div class="events" id="events">
		<div class="wrap">
			<div class="events-top">
			<div class="intro">
				<h2 class="title">Latest&nbsp;&nbsp;&nbsp;Events</h2>
				<h3 class="subtitle">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo.</h3>
			</div>
			 <div class="section group">
				<div class="col_1_of_3 span_1_of_3">
					<div class="grid_img">
						<img src="/assets/pic17.jpg" alt="">
					</div>
							<div class="team_description">
								<h4>Lorem ipsum - <span>dolor sit</span></h4>
								<p class="team_text">There is no one who loves pain itself, who seek after it and wants to have it, simply because it is pain...</p>
							</div>
						   <div class="links">
								<ul>
									<li><a href="#"><img src="/assets/blog-icon1.png" title="date"><span>June 14, 2013</span></a></li>
									<li><a href="#"><img src="/assets/blog-icon2.png" title="Admin"><span>Admin</span></a></li>
									<li class="last"><a href="#"><img src="/assets/blog-icon3.png" title="Comments"><span>No Comments</span></a></li>
								</ul>
							</div>
					</div>
				<div class="col_1_of_3 span_1_of_3">
					<div class="grid_img">
					   <img src="/assets/pic18.jpg" alt="">
					</div>
						<div class="team_description">
							  <h4>Lorem ipsum - <span>dolor sit</span></h4>
							  <p class="team_text">There is no one who loves pain itself, who seek after it and wants to have it, simply because it is pain...</p>
						</div>
						 <div class="links">
								<ul>
									<li><a href="#"><img src="/assets/blog-icon1.png" title="date"><span>June 14, 2013</span></a></li>
									<li><a href="#"><img src="/assets/blog-icon2.png" title="Admin"><span>Admin</span></a></li>
									<li class="last"><a href="#"><img src="/assets/blog-icon3.png" title="Comments"><span>No Comments</span></a></li>
								</ul>
							</div>
				</div>
				<div class="col_1_of_3 span_1_of_3">
					<div class="grid_img">
					  <img src="/assets/pic19.jpg" alt="">
					</div>
						<div class="team_description">
							  <h4>Lorem ipsum - <span>dolor sit</span></h4>
							  <p class="team_text">There is no one who loves pain itself, who seek after it and wants to have it, simply because it is pain...</p>
						</div>
						 <div class="links">
								<ul>
									<li><a href="#"><img src="/assets/blog-icon1.png" title="date"><span>June 14, 2013</span></a></li>
									<li><a href="#"><img src="/assets/blog-icon2.png" title="Admin"><span>Admin</span></a></li>
									<li class="last"><a href="#"><img src="/assets/blog-icon3.png" title="Comments"><span>No Comments</span></a></li>
								</ul>
							</div>
				</div>
				<div class="clear"></div>
			 </div>
		</div>
	 </div>
	</div>
	<div class="contact" id="contact">
		<div class="wrap">
			<div class="events-top">
			<div class="intro">
				<h2 class="title">Contact</h2>
				<h3 class="subtitle">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo.</h3>
			</div>
			<div class="form">
				<form class="cmxform" id="contactForm" method="post">
					<div class="to">
						<input type="text" class="text" value="Name" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Name';}">
						<input type="text" class="text" value="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}" style="margin-left: 10px">
					</div>
					<div class="to">
						<input type="text" class="text" value="Your Website" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Your Website';}">
						<input type="text" class="text" value="Subject" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Subject';}" style="margin-left: 10px">
					</div>
					<div>
					   <textarea value="Message:" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Message';}">Message:</textarea>
					</div>
					<div>
						<a href="#" class="submit">Submit</a>
					</div>
			   </form>
			</div>
		</div>
	</div>
  </div>
 <div class="footer-bottom">
	<div class="wrap">
		<div class="copy">
			<p>Copyright &copy; 2014.Company name All rights reserved.More Templates <a href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a> - Collect from <a href="http://www.cssmoban.com/" title="网页模板" target="_blank">网页模板</a></p>
		</div>
	</div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=GBK">
    <title>公主连接</title>
    <meta name="keywords" content="Princess Connect Re:Dive">
    <meta name="description" content="Princess Connect Re:Dive">
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7">
    <link rel="icon" href="/assets/pcr.jpg" type="image/jpeg"/>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application' , media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'style' , media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= yield :self_style %>
    <%= yield :login %>
    <%= yield :register %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'jquery-1.8.3.min', 'data-turbolinks-track': 'reload' %>

    <%= yield :self_js %>
    <%= yield :register_js %>
  </head>

  <body>
    <div class="header-top">
        <div class="wrap">
            <div class="logo">
                <a href="#"><img src="/assets/top_logo.png" alt=""></a>
            </div>
            <ul class="follow_icon">
                <li><a href="#"><img src="/assets/fb.png" alt=""></a></li>
                <li><a href="#"><img src="/assets/tw.png" alt=""></a></li>
                <li><a href="#"><img src="/assets/rss.png" alt=""></a></li>
            </ul>
            <div class="clear"></div> 
            <div class="top-nav">
                <ul>
                    <li class="active"><%= link_to "Home",root_path%></li> |
                    <li class="active"><%= link_to "Map",maps_path%></li> |
                    <li class="active"><%= link_to "Weapon",weapons_path%></li> |
                    <li class="active"><%= link_to "Princess",princesses_path%></li> 
<!--                     <li><a href="#contact" class="scroll">Pri</a></li> -->
                </ul>
            </div>
        </div>
    </div>   
    <%= yield %>
  </body>
</html>
<script type="text/javascript">
jQuery(document).ready(function($) {
    $(".scroll").click(function(event){     
        event.preventDefault();
        $('html,body').animate({scrollTop:$(this.hash).offset().top},1200);
    });
});
</script>

app/views/princesses/_form.html.erb
<%= form_for(@princess) do |f| %>
    <%= f.file_field :icon, class: "form-control" %>
    <%= f.text_field :cn_name,class: "form-control"%>
    <%= f.submit '提交', class:"btn btn-primary submit"%>
<%end%>

app/views/princesses/index.html.erb
<div class="header-bottom">  
     <div class="wrap">
        <div class="header-left" id="home">
          <section>
            <ul class="lb-album" >
                <%if @princesses.count > 0%>
                    <%@princesses.each do |princess|%>
                        <li>
                            <a href="#image-1">
                                <img src="<%=princess.icon_url%>" alt="image01">
                                <span><%=princess.cn_name%></span>
                            </a>
                            <div class="lb-overlay" id="image-1">
                                <a href="#page" class="lb-close">x Close</a>
                                <img src="<%=princess.icon_url%>" alt="image01">
                                <div>
                                    <h3>pointe <span>/point/</span></h3>
                                    <p>Dance performed on the tips of the toes</p>
                                </div>
                            </div>
                        </li>
                    <%end%>
                <%end%>
                <div class="clear"></div>
            </ul>
        </section>
        <div class="clear"></div>
    </div>
 </div>
 <div class="clear"></div>

app/views/princesses/new.html.erb
<%= render 'form'%>